- name: Create local opt
  file:
    path: /home/vagrant/.local/opt
    owner: vagrant
    state: directory
- name: Fetch radare
  git:
    repo: https://github.com/radareorg/radare2
    dest: /home/vagrant/.local/opt/radare2
    clone: yes
    update: yes
  register: radaregit
- name: Install radare
  command: /home/vagrant/.local/opt/radare2/sys/install.sh
  when: radaregit.changed
- name: Radare plugins index
  command: r2pm -U
- name: Install r2ghidra
  command: r2pm -ci r2ghidra
