- name: Install some hackertools using apt
  apt:
    name: [wireshark, dirb, gobuster, python3-pwntools, ropper, python3-ropgadget, python3-tqdm]
- name: Let wireshark capture packets
  capabilities:
    path: /usr/bin/dumpcap
    capability: "cap_net_raw,cap_net_admin=eip"
    state: present
- name: Add wireshark group
  group:
    name: wireshark
    state: present
- name: Set permissions for dumpcap
  file:
    path: /usr/bin/dumpcap
    group: wireshark
    mode: o-rx
- name: Add vagrant to wireshark group
  user:
    name: vagrant
    uid: 1000
    groups: [wireshark]
- name: Run dpkg-reconfigure, to fix wireshark(???)
  shell: "DEBIAN_FRONTEND=noninteractive dpkg-reconfigure wireshark-common"
- name: Get RsaCtfTool
  git:
    repo: https://github.com/Ganapati/RsaCtfTool
    dest: /opt/RsaCtfTool
    clone: yes
    update: yes
    depth: 1
- name: Install RsaCtfTool dependencies
  command: sudo pip install --break-system-packages -r /opt/RsaCtfTool/requirements.txt
- name: All my favourite pip packages
  command: sudo pip install --break-system-packages angr
- name: Create symbolic link for RsaCtfTool
  file:
    src: "/opt/RsaCtfTool/RsaCtfTool.py"
    dest: "/usr/bin/rsactftool"
    state: link
- name: Fetch linpeas
  git:
    repo: https://github.com/carlospolop/PEASS-ng
    dest: /opt/PEASS
    clone: yes
    update: yes
    depth: 1
- name: Fetch searchsploit
  git:
    repo: https://gitlab.com/exploit-database/exploitdb
    dest: /opt/exploitdb
    clone: yes
    update: yes
    depth: 1
- name: Symlink searchsploit
  file:
    src: /opt/exploitdb/searchsploit
    dest: /usr/bin/searchsploit
    state: link

