- name: Get RsaCtfTool
  git:
    repo: https://github.com/Ganapati/RsaCtfTool
    dest: /opt/RsaCtfTool
    clone: yes
    update: yes
    depth: 1
- name: Install RsaCtfTool dependencies
  command: sudo pip install -r /opt/RsaCtfTool/requirements.txt
- name: All my favourite pip packages
  command: sudo pip install ropper ropgadget pwntools tqdm
- name: Create symbolic link for RsaCtfTool
  file:
    src: "/opt/RsaCtfTool/RsaCtfTool.py"
    dest: "/usr/bin/rsactftool"
    state: link
- name: Fetch linpeas
  git:
    repo: https://github.com/carlospolop/PEASS-ng
    dest: /opt/PEASS
    clone: yes
    update: yes
    depth: 1
- name: Fetch searchsploit
  git:
    repo: https://github.com/offensive-security/exploitdb
    dest: /opt/exploitdb
    clone: yes
    update: yes
    depth: 1
- name: Symlink searchsploit
  file:
    src: /opt/exploitdb/searchsploit
    dest: /usr/bin/searchsploit
    state: link

