- name: Install packages
  apt:
    name: [qemu-user-binfmt, patchelf]
  become: yes
- name: Fetch pwndbg
  git:
    repo: https://github.com/pwndbg/pwndbg
    dest: /home/vagrant/.local/opt/pwndbg
    clone: yes
    update: yes
  register: pwndbggit
- name: Install pwndbg
  shell: "DEBIAN_FRONTEND=noninteractive cd /home/vagrant/.local/opt/pwndbg/ && ./setup.sh"
  when: pwndbggit.changed
- name: Get splitmind
  git:
    repo: https://github.com/jerdna-regeiz/splitmind
    dest: /home/vagrant/.local/opt/splitmind
    clone: yes
    update: yes
- name: "Add splitmind to gdbinit"
  lineinfile:
    name: /home/vagrant/.gdbinit
    line: "source /home/vagrant/.local/opt/splitmind/gdbinit.py"
    state: present
- name: Copy splitmindrc
  copy:
    src: splitmindrc.py
    dest: /home/vagrant/.splitmindrc.py
- name: "Add splitmindrc to gdbinit"
  lineinfile:
    name: /home/vagrant/.gdbinit
    line: "source /home/vagrant/.splitmindrc.py"
    state: present
